### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jaikishantulswani** [laurynasgadl/amplitude-php#2]
@laurynasgadl It is not related to this repository, I approach through this manner because I havnt found any security contact associated with Hostinger, can you please let me know the security folks so that I can discuss something related to bug bounty.

Thank You !

**Comment by laurynasgadl** [comment]
Hey! You can get in touch with Hostinger's security team by filling out the form at the bottom here: https://www.hostinger.com/responsible-disclosure-policy

**Comment by jaikishantulswani** [comment]
@laurynasgadl I already sent a report using this but now I have found an another issue and for this I would like to discuss something before submitting it, can I have your twitter handle so that I can dm you.

**Comment by laurynasgadl** [comment]
@jaikishantulswani They have an email address that you can contact them directly on - security@hostinger.com

**Comment by kibernautas** [comment]
Or you can ask me if you want :) arnoldas.radisauskas@hostinger.com

**Comment by jaikishantulswani** [comment]
Hi @arnoldasr Can you please check your mail as I shot you some details which I would like to ask before submitting another issue.
